trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: terraform-vars

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV4@4
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    workingDirectory: 'infra/vm'
    command: 'init'
    backendServiceArm: 'terraform-interview'
    backendAzureRmResourceGroupName: 'tf-backend-fordemopratice-rg'
    backendAzureRmStorageAccountName: 'tfstate12345milan'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: "dev.terraform.tfstate"

- task: TerraformTaskV4@4
  displayName: Terraform Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: 'infra/vm'
    environmentServiceNameAzureRM: 'terraform-interview'
    commandOptions: '-var "admin_username=$(vm_username)" -var "admin_password=$(vm_password)"'

- task: TerraformTaskV4@4
  displayName: 'Terraform Import RG'
  inputs:
    provider: 'azurerm'
    command: 'custom'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra/vm'
    customCommand: 'import azurerm_resource_group.rg "/subscriptions/6349a94a-bcc7-4da7-8f36-2f6bc3017bf7/resourceGroups/rg-selfhosted-dev"'
    environmentServiceNameAzureRM: 'terraform-interview'
- task: TerraformTaskV4@4
  displayName: Terraform Apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: 'infra/vm'
    environmentServiceNameAzureRM: 'terraform-interview'
    commandOptions: '-auto-approve -var "admin_username=$(vm_username)" -var "admin_password=$(vm_password)"'